-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT into friend (name) VALUES ('John');
-- INSERT into friend (name) VALUES ('Wick');
