import type { NextPage } from "next";
import Head from "next/head";
import type { GetServerSideProps } from "next";
import { client } from "../utils/client";
import {
  GetFriends,
  GetFriendsQuery,
  GetFriendsQueryVariables,
} from "../generated/graphql";
import Auth from "../components/Auth";

interface Props {
  friends: GetFriendsQuery["friend"];
}

const Home: NextPage<Props> = ({ friends }) => {
  console.log("friends", friends);
  return (
    <div>
      <Head>
        <title>Zoto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Auth />
      <main>
        {friends?.map((item) => (
          <div key={item.id}>{item?.name}</div>
        ))}
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  return client
    .query<GetFriendsQuery, GetFriendsQueryVariables>(GetFriends)
    .toPromise()
    .then((d) => {
      return {
        props: { friends: d?.data?.friend },
      };
    })
    .catch((e) => {
      return {
        props: {},
      };
    });
};
